package hr.fer.oprpp1.hw02.prob1;


/** Class for each token generated by Lexer.
 * 
 * @author Toni Polanec
 * @see  hr.fer.oprpp1.hw02.prob1.Lexer
 */
public class Token {
	
	/**<p> Value of a token. </p>*/
	Object value;
	
	/**<p> Type of a token. </p>*/
	TokenType type;

	
	/** Constructor for Token class.
	 * 
	 * @param type of a token we want to define
	 * @param value we want to give this token
	 */
	public Token(TokenType type, Object value) {
		this.value = value;
		this.type = type;
	}
	
	
	/** Returns value of a token.
	 * 
	 * @return value of a token 
	 */
	public Object getValue() {
		return value;
	}
	
	/** Returns type of a token.
	 * 
	 * @return type of a token or <code>null</code> it token doesn't have defined type
	 */
	public TokenType getType() {
		return type;
	}

}
